### PR TITLE
issues with compilation and github issues

### PR DESCRIPTION
**Pull request by BegleitPanzer**
read the updated README.md

### CODE REVIEW

**Comment by SpaceWalkerRS** [comment]
I don't know why but issues were turned off on this repo, I enabled them. The error occurs because you are running Gradle with java 8, while both Fabric Loom and Ploceus require java 17 to be run. Once the development environment is set up, you can import the project into your IDE and you're able to run the game with java 8. I hope that helps.

**Comment by BegleitPanzer** [comment]
yeah that actually helps alot

**Comment by BegleitPanzer** [comment]
can you tell me what this is exactly, I am kinda busy right now but when I tried compiling I kinda thought I would compile it and see what it is since the description is kinda vague

**Comment by SpaceWalkerRS** [comment]
It's a custom server for the Bismuth, a community of technical Minecraft players. It has some custom features, most of which weren't developed by me. I just helped porting it to Fabric through Ornithe.

**Comment by BegleitPanzer** [comment]
it is 1.12.2 right?

**Pull request closed without merging**
